### ISSUE TITLE
leftjoin alias error

### ISSUE THREAD

**Issue by Tonkong** [yii2tech/ar-softdelete#19]
$query = xx::find()->alias('t1')->select('t1.aa')
            ->where(['>', 't2.aa', 0])
            ->leftJoin(yy::tableName() . ' t2', 't1.aa=t2.aa');
        $deals = $query->orderBy('t2.aa desc')->limit(10)->asArray()->all();
error：
Column not found: 1054 Unknown column 'xx.is_delete' in 'where clause'
The SQL being executed was: SELECT `t1`.`aa` FROM `xx` `t1` LEFT JOIN `yy` `t2` ON t1.aa=t2.aa WHERE (`t2`.`aa` > 0) AND (xx.`is_delete`=0)

**Comment by klimov-paul** [comment]
Unable to reproduce.
Added unit test for verification: 2386777c264fc3f5fdc467cf03a31651293f8f88

**Comment by agSoftDUCK** [comment]
@Tonkong I assume that in `::find()` the method `deleted()` was called since I don't see it in the example.

@klimov-paul In the unit test `->alias()` was called before `->deleted()` but if you call them in the opposite order the condition attributes are not normalized with the alias.

Is that the expected behavior?

`$query->deleted()->alias('t1')` shall throw an error? If so that must be documented.
