### ISSUE TITLE
soft delete on delete cascade foreign key

### ISSUE THREAD

**Issue by biladina** [yii2tech/ar-softdelete#26]
### What steps will reproduce the problem?
```
CREATE TABLE `Customer`
(
   `id` integer NOT NULL AUTO_INCREMENT,
   `name` varchar(64) NOT NULL,
   `address` varchar(64) NOT NULL,
   `phone` varchar(20) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE InnoDB;

CREATE TABLE `Purchase`
(
   `id` integer NOT NULL AUTO_INCREMENT,
   `customerId` integer NOT NULL,
   `itemId` integer NOT NULL,
   `amount` integer NOT NULL,
    PRIMARY KEY (`id`)
    FOREIGN KEY (`customerId`) REFERENCES `Customer` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`itemId`) REFERENCES `Item` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
) ENGINE InnoDB;
```

I have mysql table like this with foreign key to another table and I set ON DELETE CASCADE

### What is the expected result?
if I perform soft delete record on table Customer, the contain record on Purchase table should mark as soft deleted

### What do you get instead?
when I 'soft deleted' record on table Customer, the contain record on Purchase table not mark as soft deleted.

I tried both command, `softDelete` and `safeDelete`, it still just mark soft deleted on table Customer, not on Purchase table..

### Additional info

| Q                     | A
| --------------------- | ---
| This Package Version  | 1.0.4
| Yii Framework Version | 2.0.38
| PHP version           |  7.4.9
| Operating system      | Windows 10 build 2004

**Comment by klimov-paul** [comment]
Unfortunally, I can not support such feature in this package. Its implementation produces too many questions and potential problems.

The main concern is program performance. In order to implement cascade soft deletion we need to iterate over *all* related records applying soft delete for them. Without such iteration there is no way to get records, which relate to the ones related to first deleted record.

For example: assume we have 'user', which has related 'credit_card', which has related 'payment'. If we soft-delete user, in the end all payments should also be soft deleted, to achieve this we need to pull **all** user's credit cards from database, soft delete them, then find all payments related to these cards and then soft-delete them.
In the end we may need to iterate over half of the database record to achive the goal.

If need to soft-delete some related records in cascade you can use [SoftDeleteBehavior::EVENT_AFTER_SOFT_DELETE](https://github.com/yii2tech/ar-softdelete#events-).

As an alternative you can setup a set of database triggers to achive such behavior.
